export type ChartConfig = {
  [k in string]: {
    label?: React.ReactNode;
    icon?: React.ComponentType;
  } & (
    | { color?: string; theme?: never }
    | { color?: never; theme: Record<string, string> }
  );
};

export const regions = ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Bali', 'Semarang', 'Makassar', 'Palembang', 'Yogyakarta', 'Denpasar'];
export const products = ['Premium Rice', 'Instant Noodles Pack', 'Sumatran Coffee Beans', 'Palm Cooking Oil', 'Jasmine Tea', 'Soy Sauce', 'Chili Sauce', 'Canned Sardines', 'Coconut Milk', 'Shrimp Crackers'];
export const vendors = ['Pangan Makmur', 'Sumber Rejeki', 'Agro Lestari', 'Warung Ibu', 'Toko Kelontong Sejahtera'];

export const salesOverTimeData = [
  { month: 'January', sales: 22000000 },
  { month: 'February', sales: 21000000 },
  { month: 'March', sales: 25000000 },
  { month: 'April', sales: 27000000 },
  { month: 'May', sales: 29000000 },
  { month: 'June', sales: 31000000 },
];

export const salesByProductData = [
  { product: 'Premium Rice', sales: 5250000 },
  { product: 'Instant Noodles Pack', sales: 4800000 },
  { product: 'Sumatran Coffee Beans', sales: 3500000 },
  { product: 'Palm Cooking Oil', sales: 3200000 },
  { product: 'Jasmine Tea', sales: 2800000 },
  { product: 'Soy Sauce', sales: 2500000 },
  { product: 'Chili Sauce', sales: 1800000 },
];

export const recentSales = [
    { id: 1, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 7529100 },
    { id: 2, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 14494950 },
    { id: 3, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 1634850 },
    { id: 4, product: 'Palm Cooking Oil', vendor: 'Warung Ibu', region: 'Medan', amount: 14795250 },
    { id: 5, product: 'Jasmine Tea', vendor: 'Toko Kelontong Sejahtera', region: 'Bali', amount: 13613850 },
    { id: 6, product: 'Soy Sauce', vendor: 'Pangan Makmur', region: 'Semarang', amount: 1387650 },
    { id: 7, product: 'Chili Sauce', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 13636650 },
    { id: 8, product: 'Canned Sardines', vendor: 'Agro Lestari', region: 'Palembang', amount: 6816750 },
    { id: 9, product: 'Coconut Milk', vendor: 'Warung Ibu', region: 'Yogyakarta', amount: 11419500 },
    { id: 10, product: 'Shrimp Crackers', vendor: 'Toko Kelontong Sejahtera', region: 'Denpasar', amount: 12474000 },
    { id: 11, product: 'Premium Rice', vendor: 'Sumber Rejeki', region: 'Jakarta', amount: 12311400 },
    { id: 12, product: 'Instant Noodles Pack', vendor: 'Agro Lestari', region: 'Surabaya', amount: 9566400 },
    { id: 13, product: 'Sumatran Coffee Beans', vendor: 'Warung Ibu', region: 'Bandung', amount: 1747200 },
    { id: 14, product: 'Palm Cooking Oil', vendor: 'Toko Kelontong Sejahtera', region: 'Medan', amount: 12839550 },
    { id: 15, product: 'Jasmine Tea', vendor: 'Pangan Makmur', region: 'Bali', amount: 5157450 },
    { id: 16, product: 'Soy Sauce', vendor: 'Sumber Rejeki', region: 'Semarang', amount: 8168850 },
    { id: 17, product: 'Chili Sauce', vendor: 'Agro Lestari', region: 'Makassar', amount: 7724850 },
    { id: 18, product: 'Canned Sardines', vendor: 'Warung Ibu', region: 'Palembang', amount: 12688350 },
    { id: 19, product: 'Coconut Milk', vendor: 'Toko Kelontong Sejahtera', region: 'Yogyakarta', amount: 11838900 },
    { id: 20, product: 'Shrimp Crackers', vendor: 'Pangan Makmur', region: 'Denpasar', amount: 1534800 },
    { id: 21, product: 'Premium Rice', vendor: 'Agro Lestari', region: 'Jakarta', amount: 12743400 },
    { id: 22, product: 'Instant Noodles Pack', vendor: 'Warung Ibu', region: 'Surabaya', amount: 11439000 },
    { id: 23, product: 'Sumatran Coffee Beans', vendor: 'Toko Kelontong Sejahtera', region: 'Bandung', amount: 7093950 },
    { id: 24, product: 'Palm Cooking Oil', vendor: 'Pangan Makmur', region: 'Medan', amount: 9727650 },
    { id: 25, product: 'Jasmine Tea', vendor: 'Sumber Rejeki', region: 'Bali', amount: 7600500 },
    { id: 26, product: 'Soy Sauce', vendor: 'Agro Lestari', region: 'Semarang', amount: 3865350 },
    { id: 27, product: 'Chili Sauce', vendor: 'Warung Ibu', region: 'Makassar', amount: 9934500 },
    { id: 28, product: 'Canned Sardines', vendor: 'Toko Kelontong Sejahtera', region: 'Palembang', amount: 12946050 },
    { id: 29, product: 'Coconut Milk', vendor: 'Pangan Makmur', region: 'Yogyakarta', amount: 10491300 },
    { id: 30, product: 'Shrimp Crackers', vendor: 'Sumber Rejeki', region: 'Denpasar', amount: 7258650 },
    { id: 31, product: 'Premium Rice', vendor: 'Warung Ibu', region: 'Jakarta', amount: 13100250 },
    { id: 32, product: 'Instant Noodles Pack', vendor: 'Toko Kelontong Sejahtera', region: 'Surabaya', amount: 5365350 },
    { id: 33, product: 'Sumatran Coffee Beans', vendor: 'Pangan Makmur', region: 'Bandung', amount: 6717150 },
    { id: 34, product: 'Palm Cooking Oil', vendor: 'Sumber Rejeki', region: 'Medan', amount: 12588450 },
    { id: 35, product: 'Jasmine Tea', vendor: 'Agro Lestari', region: 'Bali', amount: 3776100 },
    { id: 36, product: 'Soy Sauce', vendor: 'Warung Ibu', region: 'Semarang', amount: 1302750 },
    { id: 37, product: 'Chili Sauce', vendor: 'Toko Kelontong Sejahtera', region: 'Makassar', amount: 10309050 },
    { id: 38, product: 'Canned Sardines', vendor: 'Pangan Makmur', region: 'Palembang', amount: 9193800 },
    { id: 39, product: 'Coconut Milk', vendor: 'Sumber Rejeki', region: 'Yogyakarta', amount: 8200200 },
    { id: 40, product: 'Shrimp Crackers', vendor: 'Agro Lestari', region: 'Denpasar', amount: 5569800 },
    { id: 41, product: 'Premium Rice', vendor: 'Toko Kelontong Sejahtera', region: 'Jakarta', amount: 9274500 },
    { id: 42, product: 'Instant Noodles Pack', vendor: 'Pangan Makmur', region: 'Surabaya', amount: 11461800 },
    { id: 43, product: 'Sumatran Coffee Beans', vendor: 'Sumber Rejeki', region: 'Bandung', amount: 8389050 },
    { id: 44, product: 'Palm Cooking Oil', vendor: 'Agro Lestari', region: 'Medan', amount: 9724950 },
    { id: 45, product: 'Jasmine Tea', vendor: 'Warung Ibu', region: 'Bali', amount: 1219950 },
    { id: 46, product: 'Soy Sauce', vendor: 'Toko Kelontong Sejahtera', region: 'Semarang', amount: 5936700 },
    { id: 47, product: 'Chili Sauce', vendor: 'Pangan Makmur', region: 'Makassar', amount: 10499850 },
    { id: 48, product: 'Canned Sardines', vendor: 'Sumber Rejeki', region: 'Palembang', amount: 11063700 },
    { id: 49, product: 'Coconut Milk', vendor: 'Agro Lestari', region: 'Yogyakarta', amount: 9676500 },
    { id: 50, product: 'Shrimp Crackers', vendor: 'Warung Ibu', region: 'Denpasar', amount: 10102350 },
    { id: 51, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Bali', amount: 13213350 },
    { id: 52, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Semarang', amount: 10871700 },
    { id: 53, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Makassar', amount: 13852050 },
    { id: 54, product: 'Palm Cooking Oil', vendor: 'Warung Ibu', region: 'Palembang', amount: 12336900 },
    { id: 55, product: 'Jasmine Tea', vendor: 'Toko Kelontong Sejahtera', region: 'Yogyakarta', amount: 14341800 },
    { id: 56, product: 'Soy Sauce', vendor: 'Pangan Makmur', region: 'Denpasar', amount: 10644000 },
    { id: 57, product: 'Chili Sauce', vendor: 'Sumber Rejeki', region: 'Jakarta', amount: 5235300 },
    { id: 58, product: 'Canned Sardines', vendor: 'Agro Lestari', region: 'Surabaya', amount: 6412800 },
    { id: 59, product: 'Coconut Milk', vendor: 'Warung Ibu', region: 'Bandung', amount: 14270400 },
    { id: 60, product: 'Shrimp Crackers', vendor: 'Toko Kelontong Sejahtera', region: 'Medan', amount: 10977150 },
    { id: 61, product: 'Premium Rice', vendor: 'Sumber Rejeki', region: 'Bali', amount: 13330500 },
    { id: 62, product: 'Instant Noodles Pack', vendor: 'Agro Lestari', region: 'Semarang', amount: 5900700 },
    { id: 63, product: 'Sumatran Coffee Beans', vendor: 'Warung Ibu', region: 'Makassar', amount: 7080450 },
    { id: 64, product: 'Palm Cooking Oil', vendor: 'Toko Kelontong Sejahtera', region: 'Palembang', amount: 1582500 },
    { id: 65, product: 'Jasmine Tea', vendor: 'Pangan Makmur', region: 'Yogyakarta', amount: 8484750 },
    { id: 66, product: 'Soy Sauce', vendor: 'Sumber Rejeki', region: 'Denpasar', amount: 10519500 },
    { id: 67, product: 'Chili Sauce', vendor: 'Agro Lestari', region: 'Jakarta', amount: 12516300 },
    { id: 68, product: 'Canned Sardines', vendor: 'Warung Ibu', region: 'Surabaya', amount: 7243950 },
    { id: 69, product: 'Coconut Milk', vendor: 'Toko Kelontong Sejahtera', region: 'Bandung', amount: 11649900 },
    { id: 70, product: 'Shrimp Crackers', vendor: 'Pangan Makmur', region: 'Medan', amount: 4701150 },
    { id: 71, product: 'Premium Rice', vendor: 'Agro Lestari', region: 'Bali', amount: 4331850 },
    { id: 72, product: 'Instant Noodles Pack', vendor: 'Warung Ibu', region: 'Semarang', amount: 11919150 },
    { id: 73, product: 'Sumatran Coffee Beans', vendor: 'Toko Kelontong Sejahtera', region: 'Makassar', amount: 9341250 },
    { id: 74, product: 'Palm Cooking Oil', vendor: 'Pangan Makmur', region: 'Palembang', amount: 10291050 },
    { id: 75, product: 'Jasmine Tea', vendor: 'Sumber Rejeki', region: 'Yogyakarta', amount: 11102700 },
    { id: 76, product: 'Soy Sauce', vendor: 'Agro Lestari', region: 'Denpasar', amount: 4049100 },
    { id: 77, product: 'Chili Sauce', vendor: 'Warung Ibu', region: 'Jakarta', amount: 3277050 },
    { id: 78, product: 'Canned Sardines', vendor: 'Toko Kelontong Sejahtera', region: 'Surabaya', amount: 831450 },
    { id: 79, product: 'Coconut Milk', vendor: 'Pangan Makmur', region: 'Bandung', amount: 13612350 },
    { id: 80, product: 'Shrimp Crackers', vendor: 'Sumber Rejeki', region: 'Medan', amount: 7148100 },
    { id: 81, product: 'Premium Rice', vendor: 'Warung Ibu', region: 'Bali', amount: 6026400 },
    { id: 82, product: 'Instant Noodles Pack', vendor: 'Toko Kelontong Sejahtera', region: 'Semarang', amount: 7956450 },
    { id: 83, product: 'Sumatran Coffee Beans', vendor: 'Pangan Makmur', region: 'Makassar', amount: 14433300 },
    { id: 84, product: 'Palm Cooking Oil', vendor: 'Sumber Rejeki', region: 'Palembang', amount: 14032950 },
    { id: 85, product: 'Jasmine Tea', vendor: 'Agro Lestari', region: 'Yogyakarta', amount: 13545600 },
    { id: 86, product: 'Soy Sauce', vendor: 'Warung Ibu', region: 'Denpasar', amount: 4048050 },
    { id: 87, product: 'Chili Sauce', vendor: 'Toko Kelontong Sejahtera', region: 'Jakarta', amount: 12466950 },
    { id: 88, product: 'Canned Sardines', vendor: 'Pangan Makmur', region: 'Surabaya', amount: 10390050 },
    { id: 89, product: 'Coconut Milk', vendor: 'Sumber Rejeki', region: 'Bandung', amount: 5586450 },
    { id: 90, product: 'Shrimp Crackers', vendor: 'Agro Lestari', region: 'Medan', amount: 1553400 },
    { id: 91, product: 'Premium Rice', vendor: 'Toko Kelontong Sejahtera', region: 'Bali', amount: 6415350 },
    { id: 92, product: 'Instant Noodles Pack', vendor: 'Pangan Makmur', region: 'Semarang', amount: 2208450 },
    { id: 93, product: 'Sumatran Coffee Beans', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 12290700 },
    { id: 94, product: 'Palm Cooking Oil', vendor: 'Agro Lestari', region: 'Palembang', amount: 7080900 },
    { id: 95, product: 'Jasmine Tea', vendor: 'Warung Ibu', region: 'Yogyakarta', amount: 8272200 },
    { id: 96, product: 'Soy Sauce', vendor: 'Toko Kelontong Sejahtera', region: 'Denpasar', amount: 8171250 },
    { id: 97, product: 'Chili Sauce', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 14128050 },
    { id: 98, product: 'Canned Sardines', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 5248200 },
    { id: 99, product: 'Coconut Milk', vendor: 'Agro Lestari', region: 'Bandung', amount: 7904550 },
    { id: 100, product: 'Shrimp Crackers', vendor: 'Warung Ibu', region: 'Medan', amount: 6023250 }
];
