export type ChartConfig = {
  [k in string]: {
    label?: React.ReactNode;
    icon?: React.ComponentType;
  } & (
    | { color?: string; theme?: never }
    | { color?: never; theme: Record<string, string> }
  );
};

export const regions = ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Bali', 'Semarang', 'Makassar', 'Palembang', 'Yogyakarta', 'Denpasar'];
export const products = ['Rice', 'Cooking Oil', 'Instant Noodles', 'Coffee', 'Tea', 'Sugar', 'Flour', 'Eggs', 'Milk', 'Bread'];
export const vendors = ['Pangan Makmur', 'Sumber Rejeki', 'Agro Lestari', 'Tani Jaya', 'Warung Kita'];

export const salesOverTimeData = [
  { month: 'January', sales: 4000 },
  { month: 'February', sales: 3000 },
  { month: 'March', sales: 5000 },
  { month: 'April', sales: 4500 },
  { month: 'May', sales: 6000 },
  { month: 'June', sales: 5500 },
];

export const salesByProductData = [
  { product: 'Rice', sales: 12500 },
  { product: 'Cooking Oil', sales: 9800 },
  { product: 'Noodles', sales: 7500 },
  { product: 'Coffee', sales: 6200 },
  { product: 'Tea', sales: 4800 },
  { product: 'Sugar', sales: 3500 },
  { product: 'Flour', sales: 2800 },
];

export const recentSales = [
  { id: 1, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 501.94 },
  { id: 2, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 966.33 },
  { id: 3, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 108.99 },
  { id: 4, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 986.35 },
  { id: 5, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 907.59 },
  { id: 6, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 92.51 },
  { id: 7, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 909.11 },
  { id: 8, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 454.45 },
  { id: 9, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 761.3 },
  { id: 10, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 831.6 },
  { id: 11, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 820.76 },
  { id: 12, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 637.76 },
  { id: 13, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 116.48 },
  { id: 14, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 855.97 },
  { id: 15, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 343.83 },
  { id: 16, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 544.59 },
  { id: 17, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 514.99 },
  { id: 18, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 845.89 },
  { id: 19, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 789.26 },
  { id: 20, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 102.32 },
  { id: 21, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 849.56 },
  { id: 22, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 762.6 },
  { id: 23, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 472.93 },
  { id: 24, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 648.51 },
  { id: 25, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 506.7 },
  { id: 26, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 257.69 },
  { id: 27, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 662.3 },
  { id: 28, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 863.07 },
  { id: 29, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 699.42 },
  { id: 30, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 483.91 },
  { id: 31, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 873.35 },
  { id: 32, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 357.69 },
  { id: 33, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 447.81 },
  { id: 34, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 839.23 },
  { id: 35, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 251.74 },
  { id: 36, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 86.85 },
  { id: 37, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 687.27 },
  { id: 38, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 612.92 },
  { id: 39, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 546.68 },
  { id: 40, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 371.32 },
  { id: 41, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 618.3 },
  { id: 42, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 764.12 },
  { id: 43, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 559.27 },
  { id: 44, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 648.33 },
  { id: 45, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 81.33 },
  { id: 46, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 395.78 },
  { id: 47, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 699.99 },
  { id: 48, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 737.58 },
  { id: 49, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 645.1 },
  { id: 50, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 673.49 },
  { id: 51, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 880.89 },
  { id: 52, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 724.78 },
  { id: 53, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 923.47 },
  { id: 54, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 822.46 },
  { id: 55, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 956.12 },
  { id: 56, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 709.6 },
  { id: 57, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 349.02 },
  { id: 58, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 427.52 },
  { id: 59, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 951.36 },
  { id: 60, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 731.81 },
  { id: 61, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 888.7 },
  { id: 62, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 393.38 },
  { id: 63, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 472.03 },
  { id: 64, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 105.5 },
  { id: 65, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 565.65 },
  { id: 66, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 701.3 },
  { id: 67, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 834.42 },
  { id: 68, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 482.93 },
  { id: 69, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 776.66 },
  { id: 70, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 313.41 },
  { id: 71, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 288.79 },
  { id: 72, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 794.61 },
  { id: 73, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 622.75 },
  { id: 74, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 686.07 },
  { id: 75, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 740.18 },
  { id: 76, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 269.94 },
  { id: 77, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 218.47 },
  { id: 78, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 55.43 },
  { id: 79, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 907.49 },
  { id: 80, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 476.54 },
  { id: 81, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 401.76 },
  { id: 82, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 530.43 },
  { id: 83, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 962.22 },
  { id: 84, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 935.53 },
  { id: 85, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 903.04 },
  { id: 86, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 269.87 },
  { id: 87, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 831.13 },
  { id: 88, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 692.67 },
  { id: 89, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 372.43 },
  { id: 90, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 103.56 },
  { id: 91, product: 'Instant Noodles Pack', vendor: 'Sumber Rejeki', region: 'Surabaya', amount: 427.69 },
  { id: 92, product: 'Sumatran Coffee Beans', vendor: 'Agro Lestari', region: 'Bandung', amount: 147.23 },
  { id: 93, product: 'Palm Cooking Oil', vendor: 'Tani Jaya', region: 'Medan', amount: 819.38 },
  { id: 94, product: 'Jasmine Tea', vendor: 'Warung Kita', region: 'Bali', amount: 472.06 },
  { id: 95, product: 'White Sugar', vendor: 'Pangan Makmur', region: 'Semarang', amount: 551.48 },
  { id: 96, product: 'All-purpose Flour', vendor: 'Sumber Rejeki', region: 'Makassar', amount: 544.75 },
  { id: 97, product: 'Organic Eggs', vendor: 'Agro Lestari', region: 'Palembang', amount: 941.87 },
  { id: 98, product: 'Fresh Milk', vendor: 'Tani Jaya', region: 'Yogyakarta', amount: 349.88 },
  { id: 99, product: 'Whole Wheat Bread', vendor: 'Warung Kita', region: 'Denpasar', amount: 526.97 },
  { id: 100, product: 'Premium Rice', vendor: 'Pangan Makmur', region: 'Jakarta', amount: 401.55 }
];
