export type ChartConfig = {
  [k in string]: {
    label?: React.ReactNode;
    icon?: React.ComponentType;
  } & (
    | { color?: string; theme?: never }
    | { color?: never; theme: Record<string, string> }
  );
};

export const regions = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'];
export const products = ['Heinz Ketchup', 'Kraft Mac & Cheese', 'Oscar Mayer Franks', 'Philadelphia Cream Cheese', 'Jell-O', 'Kool-Aid', 'Velveeta', 'Grey Poupon', 'Capri Sun', 'Claussen Pickles'];
export const vendors = ['Walmart', 'Kroger', 'Costco', 'Target', 'Whole Foods'];

export const salesOverTimeData = [
  { month: 'January', sales: 22000000 },
  { month: 'February', sales: 21000000 },
  { month: 'March', sales: 25000000 },
  { month: 'April', sales: 27000000 },
  { month: 'May', sales: 29000000 },
  { month: 'June', sales: 31000000 },
];

export const salesByProductData = [
  { product: 'Heinz Ketchup', sales: 5250000 },
  { product: 'Kraft Mac & Cheese', sales: 4800000 },
  { product: 'Oscar Mayer Franks', sales: 3500000 },
  { product: 'Philadelphia Cream Cheese', sales: 3200000 },
  { product: 'Jell-O', sales: 2800000 },
  { product: 'Capri Sun', sales: 2500000 },
  { product: 'Kool-Aid', sales: 1800000 },
];

export const recentSales = [
  { id: 1, product: 'Heinz Ketchup', vendor: 'Walmart', region: 'New York', amount: 501.94 },
  { id: 2, product: 'Kraft Mac & Cheese', vendor: 'Kroger', region: 'Los Angeles', amount: 966.33 },
  { id: 3, product: 'Oscar Mayer Franks', vendor: 'Costco', region: 'Chicago', amount: 108.99 },
  { id: 4, product: 'Philadelphia Cream Cheese', vendor: 'Target', region: 'Houston', amount: 986.35 },
  { id: 5, product: 'Jell-O', vendor: 'Whole Foods', region: 'Phoenix', amount: 907.59 },
  { id: 6, product: 'Kool-Aid', vendor: 'Walmart', region: 'Philadelphia', amount: 92.51 },
  { id: 7, product: 'Velveeta', vendor: 'Kroger', region: 'San Antonio', amount: 909.11 },
  { id: 8, product: 'Grey Poupon', vendor: 'Costco', region: 'San Diego', amount: 454.45 },
  { id: 9, product: 'Capri Sun', vendor: 'Target', region: 'Dallas', amount: 761.3 },
  { id: 10, product: 'Claussen Pickles', vendor: 'Whole Foods', region: 'San Jose', amount: 831.6 },
  { id: 11, product: 'Heinz Ketchup', vendor: 'Kroger', region: 'New York', amount: 820.76 },
  { id: 12, product: 'Kraft Mac & Cheese', vendor: 'Costco', region: 'Los Angeles', amount: 637.76 },
  { id: 13, product: 'Oscar Mayer Franks', vendor: 'Target', region: 'Chicago', amount: 116.48 },
  { id: 14, product: 'Philadelphia Cream Cheese', vendor: 'Whole Foods', region: 'Houston', amount: 855.97 },
  { id: 15, product: 'Jell-O', vendor: 'Walmart', region: 'Phoenix', amount: 343.83 },
  { id: 16, product: 'Kool-Aid', vendor: 'Kroger', region: 'Philadelphia', amount: 544.59 },
  { id: 17, product: 'Velveeta', vendor: 'Costco', region: 'San Antonio', amount: 514.99 },
  { id: 18, product: 'Grey Poupon', vendor: 'Target', region: 'San Diego', amount: 845.89 },
  { id: 19, product: 'Capri Sun', vendor: 'Whole Foods', region: 'Dallas', amount: 789.26 },
  { id: 20, product: 'Claussen Pickles', vendor: 'Walmart', region: 'San Jose', amount: 102.32 },
  { id: 21, product: 'Heinz Ketchup', vendor: 'Costco', region: 'New York', amount: 849.56 },
  { id: 22, product: 'Kraft Mac & Cheese', vendor: 'Target', region: 'Los Angeles', amount: 762.6 },
  { id: 23, product: 'Oscar Mayer Franks', vendor: 'Whole Foods', region: 'Chicago', amount: 472.93 },
  { id: 24, product: 'Philadelphia Cream Cheese', vendor: 'Walmart', region: 'Houston', amount: 648.51 },
  { id: 25, product: 'Jell-O', vendor: 'Kroger', region: 'Phoenix', amount: 506.7 },
  { id: 26, product: 'Kool-Aid', vendor: 'Costco', region: 'Philadelphia', amount: 257.69 },
  { id: 27, product: 'Velveeta', vendor: 'Target', region: 'San Antonio', amount: 662.3 },
  { id: 28, product: 'Grey Poupon', vendor: 'Whole Foods', region: 'San Diego', amount: 863.07 },
  { id: 29, product: 'Capri Sun', vendor: 'Walmart', region: 'Dallas', amount: 699.42 },
  { id: 30, product: 'Claussen Pickles', vendor: 'Kroger', region: 'San Jose', amount: 483.91 },
  { id: 31, product: 'Heinz Ketchup', vendor: 'Target', region: 'New York', amount: 873.35 },
  { id: 32, product: 'Kraft Mac & Cheese', vendor: 'Whole Foods', region: 'Los Angeles', amount: 357.69 },
  { id: 33, product: 'Oscar Mayer Franks', vendor: 'Walmart', region: 'Chicago', amount: 447.81 },
  { id: 34, product: 'Philadelphia Cream Cheese', vendor: 'Kroger', region: 'Houston', amount: 839.23 },
  { id: 35, product: 'Jell-O', vendor: 'Costco', region: 'Phoenix', amount: 251.74 },
  { id: 36, product: 'Kool-Aid', vendor: 'Target', region: 'Philadelphia', amount: 86.85 },
  { id: 37, product: 'Velveeta', vendor: 'Whole Foods', region: 'San Antonio', amount: 687.27 },
  { id: 38, product: 'Grey Poupon', vendor: 'Walmart', region: 'San Diego', amount: 612.92 },
  { id: 39, product: 'Capri Sun', vendor: 'Kroger', region: 'Dallas', amount: 546.68 },
  { id: 40, product: 'Claussen Pickles', vendor: 'Costco', region: 'San Jose', amount: 371.32 },
  { id: 41, product: 'Heinz Ketchup', vendor: 'Whole Foods', region: 'New York', amount: 618.3 },
  { id: 42, product: 'Kraft Mac & Cheese', vendor: 'Walmart', region: 'Los Angeles', amount: 764.12 },
  { id: 43, product: 'Oscar Mayer Franks', vendor: 'Kroger', region: 'Chicago', amount: 559.27 },
  { id: 44, product: 'Philadelphia Cream Cheese', vendor: 'Costco', region: 'Houston', amount: 648.33 },
  { id: 45, product: 'Jell-O', vendor: 'Target', region: 'Phoenix', amount: 81.33 },
  { id: 46, product: 'Kool-Aid', vendor: 'Whole Foods', region: 'Philadelphia', amount: 395.78 },
  { id: 47, product: 'Velveeta', vendor: 'Walmart', region: 'San Antonio', amount: 699.99 },
  { id: 48, product: 'Grey Poupon', vendor: 'Kroger', region: 'San Diego', amount: 737.58 },
  { id: 49, product: 'Capri Sun', vendor: 'Costco', region: 'Dallas', amount: 645.1 },
  { id: 50, product: 'Claussen Pickles', vendor: 'Target', region: 'San Jose', amount: 673.49 },
  { id: 51, product: 'Heinz Ketchup', vendor: 'Walmart', region: 'Phoenix', amount: 880.89 },
  { id: 52, product: 'Kraft Mac & Cheese', vendor: 'Kroger', region: 'Philadelphia', amount: 724.78 },
  { id: 53, product: 'Oscar Mayer Franks', vendor: 'Costco', region: 'San Antonio', amount: 923.47 },
  { id: 54, product: 'Philadelphia Cream Cheese', vendor: 'Target', region: 'San Diego', amount: 822.46 },
  { id: 55, product: 'Jell-O', vendor: 'Whole Foods', region: 'Dallas', amount: 956.12 },
  { id: 56, product: 'Kool-Aid', vendor: 'Walmart', region: 'San Jose', amount: 709.6 },
  { id: 57, product: 'Velveeta', vendor: 'Kroger', region: 'New York', amount: 349.02 },
  { id: 58, product: 'Grey Poupon', vendor: 'Costco', region: 'Los Angeles', amount: 427.52 },
  { id: 59, product: 'Capri Sun', vendor: 'Target', region: 'Chicago', amount: 951.36 },
  { id: 60, product: 'Claussen Pickles', vendor: 'Whole Foods', region: 'Houston', amount: 731.81 },
  { id: 61, product: 'Heinz Ketchup', vendor: 'Kroger', region: 'Phoenix', amount: 888.7 },
  { id: 62, product: 'Kraft Mac & Cheese', vendor: 'Costco', region: 'Philadelphia', amount: 393.38 },
  { id: 63, product: 'Oscar Mayer Franks', vendor: 'Target', region: 'San Antonio', amount: 472.03 },
  { id: 64, product: 'Philadelphia Cream Cheese', vendor: 'Whole Foods', region: 'San Diego', amount: 105.5 },
  { id: 65, product: 'Jell-O', vendor: 'Walmart', region: 'Dallas', amount: 565.65 },
  { id: 66, product: 'Kool-Aid', vendor: 'Kroger', region: 'San Jose', amount: 701.3 },
  { id: 67, product: 'Velveeta', vendor: 'Costco', region: 'New York', amount: 834.42 },
  { id: 68, product: 'Grey Poupon', vendor: 'Target', region: 'Los Angeles', amount: 482.93 },
  { id: 69, product: 'Capri Sun', vendor: 'Whole Foods', region: 'Chicago', amount: 776.66 },
  { id: 70, product: 'Claussen Pickles', vendor: 'Walmart', region: 'Houston', amount: 313.41 },
  { id: 71, product: 'Heinz Ketchup', vendor: 'Costco', region: 'Phoenix', amount: 288.79 },
  { id: 72, product: 'Kraft Mac & Cheese', vendor: 'Target', region: 'Philadelphia', amount: 794.61 },
  { id: 73, product: 'Oscar Mayer Franks', vendor: 'Whole Foods', region: 'San Antonio', amount: 622.75 },
  { id: 74, product: 'Philadelphia Cream Cheese', vendor: 'Walmart', region: 'San Diego', amount: 686.07 },
  { id: 75, product: 'Jell-O', vendor: 'Kroger', region: 'Dallas', amount: 740.18 },
  { id: 76, product: 'Kool-Aid', vendor: 'Costco', region: 'San Jose', amount: 269.94 },
  { id: 77, product: 'Velveeta', vendor: 'Target', region: 'New York', amount: 218.47 },
  { id: 78, product: 'Grey Poupon', vendor: 'Whole Foods', region: 'Los Angeles', amount: 55.43 },
  { id: 79, product: 'Capri Sun', vendor: 'Walmart', region: 'Chicago', amount: 907.49 },
  { id: 80, product: 'Claussen Pickles', vendor: 'Kroger', region: 'Houston', amount: 476.54 },
  { id: 81, product: 'Heinz Ketchup', vendor: 'Target', region: 'Phoenix', amount: 401.76 },
  { id: 82, product: 'Kraft Mac & Cheese', vendor: 'Whole Foods', region: 'Philadelphia', amount: 530.43 },
  { id: 83, product: 'Oscar Mayer Franks', vendor: 'Walmart', region: 'San Antonio', amount: 962.22 },
  { id: 84, product: 'Philadelphia Cream Cheese', vendor: 'Kroger', region: 'San Diego', amount: 935.53 },
  { id: 85, product: 'Jell-O', vendor: 'Costco', region: 'Dallas', amount: 903.04 },
  { id: 86, product: 'Kool-Aid', vendor: 'Target', region: 'San Jose', amount: 269.87 },
  { id: 87, product: 'Velveeta', vendor: 'Whole Foods', region: 'New York', amount: 831.13 },
  { id: 88, product: 'Grey Poupon', vendor: 'Walmart', region: 'Los Angeles', amount: 692.67 },
  { id: 89, product: 'Capri Sun', vendor: 'Kroger', region: 'Chicago', amount: 372.43 },
  { id: 90, product: 'Claussen Pickles', vendor: 'Costco', region: 'Houston', amount: 103.56 },
  { id: 91, product: 'Heinz Ketchup', vendor: 'Whole Foods', region: 'Phoenix', amount: 427.69 },
  { id: 92, product: 'Kraft Mac & Cheese', vendor: 'Walmart', region: 'Philadelphia', amount: 147.23 },
  { id: 93, product: 'Oscar Mayer Franks', vendor: 'Kroger', region: 'San Antonio', amount: 819.38 },
  { id: 94, product: 'Philadelphia Cream Cheese', vendor: 'Costco', region: 'San Diego', amount: 472.06 },
  { id: 95, product: 'Jell-O', vendor: 'Target', region: 'Dallas', amount: 551.48 },
  { id: 96, product: 'Kool-Aid', vendor: 'Whole Foods', region: 'San Jose', amount: 544.75 },
  { id: 97, product: 'Velveeta', vendor: 'Walmart', region: 'New York', amount: 941.87 },
  { id: 98, product: 'Grey Poupon', vendor: 'Kroger', region: 'Los Angeles', amount: 349.88 },
  { id: 99, product: 'Capri Sun', vendor: 'Costco', region: 'Chicago', amount: 526.97 },
  { id: 100, product: 'Claussen Pickles', vendor: 'Target', region: 'Houston', amount: 401.55 }
];
